# CI jobs

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: build wifi-img-streamer example using build script
      run: docker run --rm -v ${PWD}:/module bitcraze/aideck tools/build/build

    - name: build test_camera example
      run: docker run --rm -v ${PWD}:/module bitcraze/aideck tools/build/make-example examples/other/test_functionalities/test_camera all

    - name: build uart_send_char example
      run: docker run --rm -v ${PWD}:/module bitcraze/aideck tools/build/make-example examples/other/test_functionalities/uart_send_char all

    - name: build com-test example
      run: docker run --rm -v ${PWD}:/module bitcraze/aideck tools/build/make-example examples/other/com-test all image

    - name: rename bin file
      run: cp examples/other/com-test/BUILD/GAP8_V2/GCC_RISCV_FREERTOS/target.board.devices.flash.img aideck_gap8.bin

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ github.sha }}
        path: aideck_gap8.bin